
## POST Lat & Long
POST http://localhost:7071/api/GetRainfallByAddress
Content-Type: application/json

{"address":"1 Denison Street, North Sydney, Australia"}

### POST PROD
POST https://govhack-function.azurewebsites.net/api/GetRainfallByAddress
Content-Type: application/json

{"latitude": "-33.84","longitude": "151.21"}